CREATE TABLE  adjuster_dim (adjuster_dim_id integer DEFAULT nextval('adjuster_dim_adjuster_dim_id_seq'::regclass),
 adjuster_id integer NOT NULL,
 first_name character varying(255),
 middle_name character varying(255),
 last_name character varying(255),
 phone_no character varying(255),
 extension character varying(255),
 cell_no character varying(255),
 fax character varying(255),
 email character varying(255),
 is_verified boolean,
 street_address character varying(255),
 apartment character varying(255),
 city character varying(255),
 state character varying(20),
 zip character varying(10),
 comments text,
 count integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (adjuster_id, adjuster_dim_id));

CREATE TABLE  adjuster_insurance_dim (adjuster_insurance_dim_id integer DEFAULT nextval('adjuster_insurance_dim_billing_adjuster_insurances_id_seq'::regclass),
 billing_adjuster_insurances_id integer NOT NULL,
 adjuster_id integer NOT NULL,
 insurance_id integer NOT NULL,
 is_verified boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (adjuster_insurance_dim_id, billing_adjuster_insurances_id));

CREATE TABLE  appeal_status_dim (appeal_status_dim_id integer DEFAULT nextval('appeal_status_dim_appeal_status_dim_id_seq'::regclass),
 appeal_status_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (appeal_status_dim_id, appeal_status_id));

CREATE TABLE  appointment_fact (appointment_fact_id integer DEFAULT nextval('appointment_fact_appointment_fact_id_seq'::regclass),
 appointment_id integer NOT NULL,
 patient_id integer,
 case_id integer,
 accident_date date,
 case_type_id integer,
 scheduled_date_time timestamp with time zone,
 evaluation_date_time timestamp with time zone,
 facility_id integer,
 facility_location_id integer,
 speciality_id integer,
 appointment_type_id integer,
 provider_id integer,
 technician_id integer,
 reading_provider_id integer,
 physician_id integer,
 clinic_id integer,
 clinic_location_id integer,
 cd_image text,
 patient_appointment_status_id integer,
 appointment_status_id integer,
 appointment_priority_id integer,
 confirmation_status_id integer,
 is_cancelled integer,
 cancelled_comments text,
 is_speciality_base boolean,
 billable boolean,
 pickup_type character varying(255),
 pickup_address character varying(255),
 pickup_suite character varying(255),
 pickup_city character varying(255),
 pickup_state character varying(255),
 pickup_zip character varying(10),
 dropoff_type character varying(255),
 dropoff_address character varying(255),
 dropoff_suite character varying(255),
 dropoff_city character varying(255),
 dropoff_state character varying(255),
 dropoff_zip character varying(10),
 date_of_check_in date,
 time_of_check_in TIME,
 date_of_check_out date,
 time_of_check_out TIME,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 time_id integer,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (appointment_id, appointment_fact_id));

CREATE TABLE  appointment_priority_dim (appointment_priority_dim_id integer DEFAULT nextval('appointment_priority_dim_appointment_priority_dim_id_seq'::regclass),
 appointment_priority_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (appointment_priority_dim_id, appointment_priority_id));

CREATE TABLE  appointment_status_dim (appointment_status_dim_id integer DEFAULT nextval('appointment_status_dim_appointment_status_dim_id_seq'::regclass),
 appointment_status_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (appointment_status_dim_id, appointment_status_id));

CREATE TABLE  appointment_type_dim (appointment_type_dim_id integer DEFAULT nextval('appointment_type_dim_appointment_type_dim_id_seq'::regclass),
 appointment_type_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 qualifier character varying(255),
 description text,
 is_all_cpt_codes boolean,
 enable_cpt_codes boolean,
 is_editable boolean,
 avoid_checkedin boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (appointment_type_id, appointment_type_dim_id));

CREATE TABLE  appointment_visit_status_dim (appointment_visit_status_dim_id integer DEFAULT nextval('appointment_visit_status_dim_appointment_visit_status_dim_i_seq'::regclass),
 appointment_visit_status_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (appointment_visit_status_dim_id, appointment_visit_status_id));

CREATE TABLE  appointments_codes_dim (appointment_code__dim_id integer DEFAULT nextval('appointments_codes_dim_appointment_code__dim_id_seq'::regclass),
 appointment_code_id integer,
 appointment_id integer,
 billing_code_id integer,
 code_type_id integer,
 code_type_name character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (appointment_code__dim_id,appointment_code_id));

CREATE TABLE  attorney_dim (attorney_dim_id integer DEFAULT nextval('attorney_dim_attorney_dim_id_seq'::regclass),
 attorney_id integer NOT NULL,
 first_name character varying(255),
 middle_name character varying(255),
 last_name character varying(255),
 phone_no character varying(255),
 extension character varying(255),
 cell_no character varying(255),
 fax character varying(255),
 email character varying(255),
 is_verified boolean,
 street_address character varying(255),
 apartment character varying(255),
 city character varying(255),
 state character varying(255),
 zip character varying(255),
 comments text,
 count integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (attorney_dim_id, attorney_id)); 

CREATE TABLE  attorney_firm_dim (attorney_firm_dim_id integer DEFAULT nextval('attorney_firm_dim_attorney_firm_id_seq'::regclass),
 attorney_firm_id integer NOT NULL,
 attorney_id integer NOT NULL,
 firm_id integer,
 is_verified boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (attorney_firm_id, attorney_id));

 CREATE TABLE available_doctors_dim (available_doctors_dim_id integer DEFAULT nextval('available_doctors_dim_available_doctors_dim_id_seq'::regclass),
 available_doctors_id integer,
 start_date  timestamp with time zone,
 end_date timestamp with time zone,
 no_of_slots integer,
 doctor_id integer,
 facility_location_id  integer,
 available_speciality_id integer,
 supervisor_id integer,
 is_provider_assignment boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone,
 updated_at timestamp with time zone,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY(available_doctors_id,available_doctors_dim_id));

CREATE TABLE available_specialities_dim (available_specialities_dim_id integer DEFAULT nextval('available_specialities_dim_available_specialities_dim_id_seq'::regclass),
 available_specialities_id integer,
 start_date  timestamp with time zone,
 end_date timestamp with time zone,
 end_date_for_recurrence timestamp with time zone,
 no_of_doctors integer,
 no_of_slots integer,
 end_after_occurences integer,
 number_of_entries integer,
 speciality_id integer,
 facility_location_id  integer,
 recurrence_ending_criteria_id integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone,
 updated_at timestamp with time zone,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY(available_specialities_id,available_specialities_dim_id));


CREATE TABLE  bill_recipient_type_dim (bill_recipient_type_dim_id integer DEFAULT nextval('bill_recipient_type_dim_bill_recipient_type_dim_id_seq'::regclass),
 bill_recipient_type_id integer,
 name character varying(255),
 slug character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (bill_recipient_type_dim_id,bill_recipient_type_id));

CREATE TABLE  bill_status_dim (bill_status_dim_id integer DEFAULT nextval('bill_status_dim_bill_status_dim_id_seq'::regclass),
 bill_status_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 use_for_bill boolean,
 use_for_invoice boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (bill_status_dim_id, bill_status_id));

CREATE TABLE  billing_codes_dim (billing_code_dim_id integer DEFAULT nextval('billing_codes_dim_billing_code_dim_id_seq'::regclass),
 billing_code_id integer,
 name character varying(255),
 code_type_name character varying(255),
 code_type_id integer,
 description text,
 short_description text,
 medium_description text,
 long_description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (billing_code_dim_id,billing_code_id));

CREATE TABLE  billing_employment_type_dim (billing_employment_type_dim_id integer DEFAULT nextval('billing_employment_type_dim_billing_employment_type_dim_id_seq'::regclass),
 billing_employment_type_id integer,
 name character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (billing_employment_type_dim_id,billing_employment_type_id));

CREATE TABLE  billing_title_dim (billing_title_dim_id integer DEFAULT nextval('billing_title_dim_billing_title_dim_id_seq'::regclass),
 billing_title_id integer,
 name character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (billing_title_dim_id,billing_title_id));

CREATE TABLE  bills_fact_new (bill_fact_id integer DEFAULT (nextval('bills_fact_bill_fact_id_seq'::regclass))::integer,
 bill_id integer NOT NULL,
 bill_label character varying(255),
 patient_id integer,
 case_id integer,
 case_type_id integer,
 accident_date date,
 bill_date date,
 facility_id integer,
 facility_location_id integer,
 doctor_id integer,
 speciality_id integer,
 dos_from_date date,
 dos_to_date date,
 bill_status_id integer,
 payment_status_id integer,
 eor_status_id integer,
 denial_status_id integer,
 verification_status_id integer,
 packet_created_count integer,
 pom_generate_count integer,
 pom_received_count integer,
 verification_received_count integer,
 verification_sent_count integer,
 eor_count integer,
 denials_count integer,
 payment_count integer,
 bill_amount numeric,
 paid_amount numeric,
 interest_amount numeric,
 outstanding_amount numeric,
 over_payment numeric,
 write_off_amount numeric,
 duration interval,
 time_id integer,
 e_bill_status_id integer,
 bill_type character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone,
 updated_at timestamp without time zone,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (bill_id, bill_fact_id));

CREATE TABLE  bills_recipient_dim (bill_recipient_dim_id integer DEFAULT nextval('bills_recipient_dim_bill_recipient_dim_id_seq'::regclass),
 bill_recipients_ids_id integer NOT NULL ,
 bill_recipient_id integer,
 bill_id integer,
 bill_recipient_type_id integer,
 bill_recipient_type_name character varying(255),
 patient_id integer,
 case_id integer,
 employer_id integer,
 firm_id integer,
 firm_location_id integer,
 insurance_id integer,
 insurance_location_id integer,
 bill_recipient_f_name character varying(255),
 bill_recipient_m_name character varying(255),
 bill_recipient_l_name character varying(255),
 bill_recipient_location_name character varying(255),
 bill_recipient_street_address character varying(255),
 bill_recipient_floor character varying(255),
 bill_recipient_city character varying(255),
 bill_recipient_state character varying(255),
 bill_recipient_zip character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE,
 PRIMARY KEY (bill_recipient_dim_id,bill_recipients_ids_id));

CREATE TABLE  bills_visit_dim (bill_visits_relations_dim_id integer DEFAULT nextval('bill_visits_dim_bill_visits_relations_dim_id_seq'::regclass),
 bill_visits_id integer NOT NULL,
 bill_id integer,
 bill_visit_session_id integer,
 appointment_type_id integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (bill_visits_relations_dim_id, bill_visits_id));

CREATE TABLE  case_categories_dim (case_categories_dim_id integer DEFAULT nextval('case_categories_dim_case_categories_dim_id_seq'::regclass),
 case_categroy_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (case_categroy_id, case_categories_dim_id));

CREATE TABLE  case_fact_new (case_dim_id integer DEFAULT (nextval('case_fact_new_case_dim_id_seq'::regclass))::integer,
 case_id integer NOT NULL,
 patient_id integer,
 case_categroy_id integer,
 case_purpose_of_visit_id integer,
 case_type_id integer,
 case_status_id integer,
 is_transfer_case boolean,
 date_of_admission date,
 accident_date date,
 firm_id integer,
 firm_location_id integer,
 attorney_id integer,
 attorney_created_by character varying(255),
 attorney_updated_by character varying(255),
 attorney_created_at timestamp without time zone,
 attorney_updated_at timestamp without time zone,
 attorney_deleted_at timestamp without time zone,
 mailing_address character varying(255),
 mailing_apartment character varying(255),
 mailing_city character varying(255),
 mailing_state character varying(255),
 mailing_zip character varying(255),
 residential_address character varying(255),
 residential_apartment character varying(255),
 residential_city character varying(255),
 residential_state character varying(255),
 residential_zip character varying(255),
 creation_source character varying(255),
 pom_generate_count integer,
 pom_recieved_count integer,
 contact_person_id integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone,
 updated_at timestamp without time zone,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (case_dim_id, case_id));

CREATE TABLE  case_info_dim (case_insurance_firm_employer_info_dim_id integer DEFAULT nextval('case_info_dim_case_insurance_firm_employer_info_dim_id_seq'::regclass),
 kiosk_case_insurances_id integer,
 case_id integer,
 insurance_type character varying(50),
 insurance_id integer,
 insurance_location_id integer,
 insurance_name character varying(100),
 insurance_location_name character varying(100),
 insurance_street_address character varying(255),
 insurance_apartment_suite character varying(50),
 insurance_city character varying(100),
 insurance_state character varying(50),
 insurance_zip character varying(10),
 insurance_plan_id integer,
 insurance_plan_name character varying(100),
 insured_type character varying(50),
 insured_first_name character varying(50),
 insured_middle_name character varying(50),
 insured_last_name character varying(50),
 insured_relation_description character varying(100),
 insured_gender character varying(20),
 insured_ssn character varying(11),
 insured_dob date,
 claim_no character varying(50),
 policy_no character varying(50),
 wcb_no character varying(50),
 auth_no character varying(50),
 is_policy_holder boolean,
 member_id character varying(20),
 group_no character varying(50),
 adjuster_id integer,
 adjuster_first_name character varying(50),
 adjuster_middle_name character varying(50),
 adjuster_last_name character varying(50),
 insurance_created_by character varying(255),
 insurance_updated_by character varying(255),
 insurance_created_at timestamp without time zone,
 insurance_updated_at timestamp without time zone,
 insurance_deleted_at timestamp without time zone,
 kiosk_case_employers_id integer,
 employer_id integer,
 employer_type_id integer,
 employer_type_name character varying(50),
 employer_name character varying(100),
 employer_street_address character varying(255),
 employer_apartment_suite character varying(255),
 employer_city character varying(100),
 employer_state character varying(50),
 employer_zip character varying(10),
 hired_date date,
 end_date date,
 is_time_losses boolean,
 occupation character varying(100),
 employer_created_by character varying(255),
 employer_updated_by character varying(255),
 employer_created_at timestamp without time zone,
 employer_updated_at timestamp without time zone,
 employer_deleted_at timestamp without time zone,
 practice_location_id integer,
 kiosk_case_pl_created_by character varying(255),
 kiosk_case_pl_updated_by character varying(255),
 kiosk_case_pl_created_at timestamp without time zone,
 kiosk_case_pl_updated_at timestamp without time zone,
 kiosk_case_pl_deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (case_insurance_firm_employer_info_dim_id));

CREATE TABLE  case_purpose_of_visits_dim (case_purpose_of_visit_dim_id integer DEFAULT nextval('case_purpose_of_visits_dim_case_purpose_of_visit_dim_id_seq'::regclass),
 case_purpose_of_visit_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (case_purpose_of_visit_id, case_purpose_of_visit_dim_id));

CREATE TABLE  case_status_dim (case_status_dim_id integer DEFAULT nextval('case_status_dim_case_status_dim_id_seq'::regclass),
 case_status_id integer NOT NULL,
 name character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (case_status_id, case_status_dim_id));

CREATE TABLE  case_types_dim (case_type_dim_id integer DEFAULT nextval('case_types_dim_case_type_dim_id_seq'::regclass),
 case_type_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 description text,
 remainder_days integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (case_type_id, case_type_dim_id));

CREATE TABLE  ch_dim (ch_dim_id integer DEFAULT nextval('ch_dim_ch_dim_id_seq'::regclass),
 ch_id integer NOT NULL,
 name character varying(255),
 short_name character varying(255),
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (ch_dim_id,ch_id));

CREATE TABLE  ch_payer_dim (ch_payers_dim_id integer DEFAULT nextval('ch_payer_dim_ch_payers_dim_id_seq'::regclass),
 ch_payers_id integer NOT NULL,
 payer_id character varying(255),
 payer_name character varying(255),
 ch_id integer,
 insurance_id integer,
 is_professional boolean,
 is_institutional boolean,
 is_wc boolean,
 is_nf boolean,
 is_prx boolean,
 is_eob boolean,
 supp_trans character varying(255),
 states_ids jsonb,
 state_names character varying,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone,
 updated_at timestamp with time zone,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE,
 PRIMARY KEY (ch_payers_dim_id,ch_payers_id));

CREATE TABLE  clinic_location_dim (clinic_locations_dim_id integer DEFAULT nextval('clinic_locations_dim_clinic_locations_dim_id_seq'::regclass),
 clinic_locations_id integer NOT NULL,
 clinic_id integer,
 address character varying(255),
 floor character varying(255),
 city character varying(255),
 state character varying(20),
 zip character varying(10),
 email character varying(255),
 fax character varying(15),
 phone character varying(15),
 extension character varying(10),
 is_primary boolean,
 is_verified boolean,
 status character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (clinic_locations_id, clinic_locations_dim_id));

CREATE TABLE  clinics_dim (clinics_dim_id integer DEFAULT nextval('clinics_dim_clinics_dim_id_seq'::regclass),
 clinic_id integer NOT NULL,
 name character varying(255),
 is_verified boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (clinic_id, clinics_dim_id)); 

CREATE TABLE  dashboard_reports_auth (
    dashboard_reports_auth_id SERIAL PRIMARY KEY,
	user_id int,
    dashboard_type dashboard_enum,
    report_type report_enum,
    created_at timestamp with time zone  ,
    updated_at timestamp with time zone ,
    deleted_at timestamp with time zone,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE  denial_dim (denial_dim_id integer DEFAULT nextval('denial_dim_denial_dim_id_seq'::regclass),
 denial_id integer NOT NULL,
 bill_id integer,
 denial_status_id integer,
 denial_date date,
 reason text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (denial_dim_id, denial_id));

CREATE TABLE  denial_status_dim (denial_status_dim_id integer DEFAULT nextval('denial_status_dim_denial_status_dim_id_seq'::regclass),
 denial_status_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (denial_status_dim_id, denial_status_id));

CREATE TABLE  denial_type_dim (denial_type_dim_id integer DEFAULT nextval('denial_type_dim_denial_type_dim_id_seq'::regclass),
 denial_type_ids_id integer,
 denial_id integer,
 denial_type_id integer,
 denial_type_name character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (denial_type_dim_id,denial_type_ids_id));

CREATE TABLE  denial_type_dim_new (denial_type_dim_id integer DEFAULT nextval('denial_type_dim_new_denial_type_dim_id_seq'::regclass),
 denial_type_id integer,
 denials_type_name character varying(255),
 denials_slug character varying(200),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (denial_type_dim_id,denial_type_id));

CREATE TABLE  department_dim (department_dim_id integer DEFAULT nextval('department_dim_department_dim_id_seq'::regclass),
 department_id integer,
 name character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (department_dim_id,department_id));

CREATE TABLE  designation_dim (designation_dim_id integer DEFAULT nextval('designation_dim_designation_dim_id_seq'::regclass),
 designation_id integer,
 name character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (designation_dim_id,designation_id));

CREATE TABLE  e_bill_status_dim (e_bill_status_dim_id integer DEFAULT nextval('e_bill_status_dim_e_bill_status_dim_id_seq'::regclass),
 e_bill_status_id integer,
 name character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (e_bill_status_dim_id,e_bill_status_id));

CREATE TABLE  employed_by_dim (employed_by_dim_id integer DEFAULT nextval('employed_by_dim_employed_by_dim_id_seq'::regclass),
 employed_by_id integer,
 name character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (employed_by_dim_id,employed_by_id));

CREATE TABLE  employer_dim (employer_dim_id integer DEFAULT nextval('employer_dim_employer_dim_id_seq'::regclass),
 employer_id integer NOT NULL,
 employer_name character varying(255),
 street_address character varying(255),
 apartment character varying(255),
 city character varying(255),
 state character varying(20),
 zip character varying(10),
 email character varying(255),
 fax character varying(255),
 phone_no character varying(255),
 extension character varying(255),
 is_verified boolean,
 comments text,
 count integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (employer_dim_id, employer_id));

CREATE TABLE  employment_type_dim (employment_type_dim_id integer DEFAULT nextval('employment_type_dim_employment_type_dim_id_seq'::regclass),
 employment_type_id integer,
 name character varying(255),
 description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (employment_type_dim_id,employment_type_id));

CREATE TABLE  eor_dim (eor_dim_id integer DEFAULT nextval('eor_dim_eor_dim_id_seq'::regclass),
 eor_id integer NOT NULL,
 bill_id integer,
 eor_status_id integer,
 eor_amount numeric,
 eor_date date,
 eor_description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (eor_id, eor_dim_id));

CREATE TABLE  eor_status_dim (eor_status_dim_id integer DEFAULT nextval('eor_status_dim_eor_status_dim_id_seq'::regclass),
 eor_status_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (eor_status_dim_id, eor_status_id));

CREATE TABLE  eor_type_dim (eor_type_dim_id integer DEFAULT nextval('eor_type_dim_eor_type_dim_id_seq'::regclass),
 eor_type_id integer,
 eor_type_name character varying(255),
 eor_slug character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (eor_type_dim_id,eor_type_id));

CREATE TABLE  eor_type_ids_dim (eor_type_ids_dim_id integer DEFAULT nextval('eor_type_ids_dim_eor_type_ids_dim_id_seq'::regclass),
 eor_type_ids_id integer NOT NULL,
 eor_id integer,
 eor_type_id integer,
 eor_type_name character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (eor_type_ids_dim_id, eor_type_ids_id));

CREATE TABLE  facilities_dim (facility_dim_id integer DEFAULT nextval('facilities_dim_facility_dim_id_seq'::regclass),
 facility_id integer NOT NULL,
 facility_name character varying(255),
 facility_qualifier character varying(255),
 facility_billing_address character varying(255),
 facility_billing_floor character varying(255),
 facility_billing_city character varying(255),
 facility_billing_state character varying(20),
 facility_billing_zip character varying(10),
 facility_phone character varying(20),
 facility_fax character varying(15),
 facility_email character varying(255),
 tin character varying(255),
 npi character varying(255),
 ssn character varying(11),
 facility_location_address character varying(255),
 facility_location_floor character varying(100),
 facility_location_city character varying(100),
 facility_location_state character varying(100),
 facility_location_zip character varying(20),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (facility_dim_id, facility_id));      

CREATE TABLE  facility_location_dim (facility_location_dim_id integer DEFAULT nextval('facility_location_dim_facility_location_dim_id_seq'::regclass),
 facility_location_id integer NOT NULL,
 facility_id integer,
 facility_location_name character varying(255),
 facility_location_qualifier character varying(255),
 facility_location_address character varying(255),
 facility_location_floor character varying(255),
 facility_location_city character varying(255),
 facility_location_state character varying(20),
 facility_location_zip character varying(10),
 facility_location_phone character varying(15),
 facility_location_extension_no character varying(10),
 facility_location_cell_no character varying(15),
 facility_location_fax character varying(15),
 facility_location_email character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (facility_location_dim_id, facility_location_id));

CREATE TABLE  firm_location_dim (firm_location_dim_id integer DEFAULT nextval('firm_location_dim_firm_location_dim_id_seq'::regclass) ,
 firm_location_id integer NOT NULL,
 firm_id integer,
 firm_location_name character varying(255),
 is_primary_location boolean,
 is_firm_location_verified boolean,
 street_address character varying(255),
 apartment character varying(255),
 city character varying(255),
 state character varying(20),
 zip character varying(10),
 phone_no character varying(255),
 extention character varying(255),
 cell_no character varying(255),
 fax character varying(255),
 email character varying(255),
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (firm_location_dim_id,firm_location_id));

CREATE TABLE  firms_dim (firm_dim_id integer DEFAULT nextval('firms_dim_firm_dim_id_seq'::regclass),
 firm_id integer NOT NULL,
 firm_name character varying(255),
 is_firm_verified boolean,
 firm_count integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (firm_dim_id, firm_id));

CREATE TABLE  insurance_dim (insurance_dim_id integer DEFAULT nextval('insurance_dim_insurance_dim_id_seq'::regclass),
 insurance_id integer NOT NULL,
 insurance_name character varying(255),
 insurance_code character varying(255),
 is_insurance_verified boolean,
 insurance_count integer,
 is_electronic boolean,
 is_manual boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (insurance_dim_id, insurance_id));  

CREATE TABLE  insurance_location_dim (insurance_location_dim_id integer DEFAULT nextval('insurance_location_dim_insurance_location_id_seq'::regclass),
 insurance_location_id integer NOT NULL,
 insurance_id integer NOT NULL,
 insurance_location_name character varying(255),
 insurance_location_code character varying(255),
 is_insurance_location_verified boolean,
 primary_insurance boolean,
 street_address character varying(255),
 apartment character varying(255),
 city character varying(255),
 state character varying(20),
 zip character varying(10),
 phone_no character varying(255),
 extension character varying(255),
 cell_no character varying(255),
 fax character varying(255),
 email character varying(255),
 comments text,
 default_payer_id integer,
 is_associate_with_payer boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (insurance_location_id, insurance_id));

CREATE TABLE kafka_offset (kafka_offset_id integer DEFAULT nextval('kafka_offset_id_seq'::regclass),
 offset_value bigint,
 PRIMARY KEY (kafka_offset_id));

CREATE TABLE packet_bill_recipients_dim (packet_bill_recipients_dim_id integer DEFAULT nextval('packet_bill_recipients_dim_packet_bill_recipients_dim_id_seq'::regclass),
 packet_bill_recipients_id integer,
 type_id  integer,
 packet_id integer,
 bill_id integer,
 recipient_id integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone,
 updated_at timestamp with time zone,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY(packet_bill_recipients_id,packet_bill_recipients_dim_id));

CREATE TABLE  patient_dim (patient_dim_id integer DEFAULT nextval('patient_dim_patient_dim_id_seq'::regclass),
 patient_id integer NOT NULL,
 first_name character varying(255),
 middle_name character varying(255),
 last_name character varying(255),
 dob date,
 gender character(10),
 age integer,
 ssn character varying(11),
 cell_phone character varying(15),
 home_phone character varying(15),
 work_phone character varying(15),
 height_ft integer,
 height_in integer,
 weight_lbs numeric,
 marital_status character varying(50),
 is_law_enforcement_agent boolean,
 is_pregnant text,
 patient_notes text,
 patient_status character varying(50),
 is_soft_registered boolean,
 creation_source character varying(50),
 is_active boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (patient_id, patient_dim_id));

CREATE TABLE  payment_action_type_dim (payment_action_type_dim_id integer DEFAULT nextval('payment_action_type_dim_payment_action_type_dim_id_seq'::regclass),
 payment_action_type_id integer NOT NULL,
 payment_action_type_name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (payment_action_type_dim_id, payment_action_type_id));

CREATE TABLE  payment_by_dim (payment_by_dim_id integer DEFAULT nextval('payment_by_dim_payment_by_dim_id_seq'::regclass),
 payment_by_id integer NOT NULL,
 payment_by_name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (payment_by_id, payment_by_dim_id));

CREATE TABLE  payment_fact (payment_fact_id integer DEFAULT nextval('payment_fact_payment_fact_id_seq'::regclass),
 payment_id integer NOT NULL,
 bill_id integer,
 action_type_id integer,
 payment_type_id integer,
 payment_by_id integer,
 payment_status_id integer,
 check_date date,
 check_no character varying(255),
 check_amount numeric,
 description text,
 invoice_id integer,
 bulk_payment boolean,
 bulk_payment_id integer,
 recipient_id integer,
 recipient_name character varying(255),
 recipient_slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (payment_id, payment_fact_id));

CREATE TABLE  payment_status_dim (payment_status_dim_id integer DEFAULT nextval('payment_status_dim_payment_status_dim_id_seq'::regclass),
 payment_status_id integer,
 name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 use_for_bill boolean,
 use_for_invoice boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE,
 PRIMARY KEY (payment_status_dim_id, payment_status_id));

CREATE TABLE  payment_type_dim (payment_type_dim_id integer DEFAULT nextval('payment_type_dim_payment_type_dim_id_seq'::regclass),
 payment_type_id integer NOT NULL,
 payment_type_name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 use_for_bill boolean,
 use_for_invoice boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (payment_type_id, payment_type_dim_id));      

------
CREATE TABLE  physician_dim (physician_dim_id integer DEFAULT nextval('physician_dim_physician_dim_id_seq'::regclass),
 physician_id integer NOT NULL,
 first_name character varying(255),
 middle_name character varying(255),
 last_name character varying(255),
 email character varying(255),
 cell_no character varying(15),
 npi_no character varying(255),
 license_no character varying(255),
 is_verified boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (physician_id, physician_dim_id));

CREATE TABLE  physician_specialities_dim (physician_specialities_dim_id integer DEFAULT nextval('physician_specialities_dim_physician_specialities_dim_id_seq'::regclass),
 physician_specialities_id integer NOT NULL,
 physician_id integer,
 speciality_id integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (physician_specialities_dim_id, physician_specialities_id));

CREATE TABLE  pom_bills_cases_dim (bills_cases_dim_id integer DEFAULT nextval('pom_bills_cases_dim_bills_cases_dim_id_seq'::regclass),
 pom_bills_id integer,
 pom_id integer,
 bill_id integer,
 category_id integer,
 category character varying(255),
 pom_bills_created_by character varying(255),
 pom_bills_updated_by character varying(255),
 pom_bills_created_at timestamp with time zone,
 pom_bills_updated_at timestamp with time zone,
 pom_bills_deleted_at timestamp with time zone,
 pom_case_id integer,
 case_id integer,
 practice_location_id integer,
 scan_pom_upload_date date,
 pom_case_created_by character varying(255),
 pom_case_updated_by character varying(255),
 pom_case_created_at timestamp with time zone,
 pom_case_updated_at timestamp with time zone ,
 pom_case_deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE , 
 PRIMARY KEY (bills_cases_dim_id));

CREATE TABLE pom_types_dim (pom_types_dim_id integer DEFAULT nextval('pom_types_dim_pom_types_dim_id_seq'::regclass),
 pom_types_id integer,
 name  character varying(255),
 slug character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone,
 updated_at timestamp with time zone,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY(pom_types_dim_id,pom_types_id));

CREATE TABLE  poms_dim (poms_dim_id integer DEFAULT nextval('poms_dim_poms_dim_id_seq'::regclass),
 pom_id integer,
 in_nf2 integer,
 is_packet integer,
 packet_id integer,
 media_id integer,
 scan_media_id integer,
 scan_pom_upload_date date,
 received_pom_updated_by character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (poms_dim_id,pom_id));

CREATE TABLE  roles_dim (role_dim_id integer DEFAULT nextval('roles_dim_role_dim_id_seq'::regclass),
 role_id integer,
 name character varying(255),
 qualifier character varying(255),
 is_hidden boolean,
 can_finalize boolean,
 comments text,
 is_default boolean,
 slug character varying(255),
 medical_identifiers character varying(255),
 has_supervisor boolean,
 is_order integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (role_dim_id,role_id));

CREATE TABLE  specialities_dim (specialities_dim_id integer DEFAULT nextval('specialities_dim_specialities_dim_id_seq'::regclass),
 specialty_id  integer NOT NULL,
 name character varying(255),
 qualifier character varying(255),
 description text,
 time_slot integer,
 over_booking text,
 has_app boolean,
 specialty_key character varying(255),
 is_default boolean,
 is_available boolean,
 is_create_appointment boolean,
 is_editable boolean,
 comments text,
 is_multiple_visit boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (specialty_id, specialities_dim_id));

CREATE TABLE  time_dimension (time_id integer DEFAULT nextval('time_dimension_time_id_seq'::regclass),
 full_date date,
 year integer,
 quarter integer,
 month integer,
 week integer,
 day character varying(255),
 day_of_week integer,
 day_of_year integer,
 is_weekend character varying(255),
 is_holiday character varying(255), PRIMARY KEY (time_id));

CREATE TABLE  user_facilities_dim (users_relational_dim_id integer DEFAULT nextval('user_facilities_dim_users_relational_dim_id_seq'::regclass),
 user_rel_id integer NOT NULL,
 user_id integer,
 facility_id integer,
 facility_location_id integer,
 specialty_id integer,
 is_manual_specialty boolean,
 is_primary boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (user_rel_id, users_relational_dim_id));        

CREATE TABLE  users_dim (user_dim_id integer DEFAULT nextval('users_dim_user_dim_id_seq'::regclass),
 user_id integer NOT NULL,
 email character varying(255),
 role_id integer,
 role_name character varying(255),
 is_work_from_home boolean,
 allow_multiple_assignment boolean,
 last_login timestamp with time zone,
 epcs_status_id integer,
 title character varying(255),
 first_name character varying(255),
 middle_name character varying(255),
 last_name character varying(255),
 dob date,
 ssn character varying(11),
 gender character(1),
 cell_no character varying(15),
 home_phone character varying(15),
 work_phone character varying(15),
 extension character varying(255),
 emergency_name character varying(255),
 emergency_phone character varying(15),
 address character varying(255),
 apartment_suite character varying(255),
 city character varying(255),
 state character varying(255),
 zip character varying(255),
 biography text,
 hiring_date date,
 billing_title_name character varying(255),
 employed_by_name character varying(255),
 department_name character varying(255),
 designation_name character varying(255),
 employment_type_name character varying(255),
 billing_employment_type_name character varying(255),
 other character varying(255),
 medical_credentials character varying(255),
 is_individual boolean,
 spi character varying(255),
 registration_number character varying(255),
 registration_expiration_date date,
 npi character varying(255),
 upin character varying(255),
 wcb_authorization character varying(255),
 wcb_rating_code character varying(255),
 wcb_date_of_issue date,
 is_reading_provider boolean,
 is_self boolean,
 doctor_id integer,
 status integer,
 billing_title_id integer,
 employed_by_id integer,
 department_id integer,
 designation_id integer,
 employment_type_id integer,
 billing_employment_type_id integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (user_id, user_dim_id));

CREATE TABLE  verification_dim (verification_dim_id integer DEFAULT nextval('verification_dim_verification_dim_id_seq'::regclass),
 verification_id integer NOT NULL,
 bill_id integer,
 verification_received_date date,
 verification_received_description text,
 verification_status_id integer,
 appeal_status_id integer,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (verification_dim_id, verification_id));

CREATE TABLE  verification_sent_dim (verification_sent_dim_id integer DEFAULT nextval('verification_sent_dim_verification_sent_dim_id_seq'::regclass),
 verification_sent_id integer NOT NULL,
 verification_received_id integer,
 verification_sent_date date,
 verification_sent_description text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (verification_sent_dim_id, verification_sent_id));

CREATE TABLE  verification_status_dim (verification_status_dim_id integer DEFAULT nextval('verification_status_dim_verification_status_dim_id_seq'::regclass),
 verification_status_id integer NOT NULL,
 name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (verification_status_id, verification_status_dim_id));

CREATE TABLE  verification_type_dim (verification_type_dim_id integer DEFAULT nextval('verification_type_dim_verification_type_dim_id_seq'::regclass),
 verification_type_id integer,
 verification_type_name character varying(255),
 verification_slug character varying(100),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp without time zone ,
 updated_at timestamp without time zone ,
 deleted_at timestamp without time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (verification_type_dim_id,verification_type_id));

CREATE TABLE  verification_types_dim (verification_types_dim_id integer DEFAULT nextval('verification_types_dim_verification_types_dim_id_seq'::regclass),
 verification_type_ids_id integer NOT NULL,
 verification_id integer,
 verification_type_id integer,
 verification_type_name character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (verification_type_ids_id, verification_types_dim_id));       

CREATE TABLE  visit_codes_dim (visit_codes_dim_id integer DEFAULT nextval('visit_codes_dim_visit_codes_dim_id_seq'::regclass),
 visit_code_id integer,
 code_type_id integer,
 code_type_name character varying(255),
 code_name character varying(255),
 code_description text,
 visit_session_id integer,
 is_editable boolean,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE , 
 PRIMARY KEY (visit_codes_dim_id,visit_code_id));

CREATE TABLE  visit_session_state_dim (visit_session_state_dim_id integer DEFAULT nextval('visit_session_state_dim_visit_session_state_dim_id_seq'::regclass),
 visit_session_state_id integer NOT NULL,
 visit_session_state_name character varying(255),
 slug character varying(255),
 description text,
 comments text,
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (visit_session_state_dim_id, visit_session_state_id));

CREATE TABLE  visits_fact (visit_fact_id integer DEFAULT nextval('visits_fact_visit_fact_id_seq'::regclass),
 visit_id integer NOT NULL,
 appointment_id integer,
 patient_id integer,
 case_id integer,
 accident_date date,
 case_type_id integer,
 visit_date date,
 facility_id integer,
 facility_location_id integer,
 speciality_id integer,
 appointment_type_id integer,
 provider_id integer,
 technician_id integer,
 reading_provider_id integer,
 cd_image text,
 visit_session_state_id integer,
 is_amended boolean,
 template_type character varying(255),
 visit_charges numeric,
 document_uploaded boolean,
 last_uploaded_document_date date,
 time_id integer,
 visit_cpt_code_status character varying(255),
 visit_icd_code_status character varying(255),
 created_by character varying(255),
 updated_by character varying(255),
 created_at timestamp with time zone ,
 updated_at timestamp with time zone ,
 deleted_at timestamp with time zone,
 dumb_date date DEFAULT CURRENT_DATE ,
 PRIMARY KEY (visit_fact_id, visit_id));