swagger: "2.0"
info:
  version: "1.0.0"
  title: "Provider Appointments Data"
description: "This API provides appointment data for providers, including the count of cancelled, re-scheduled, and scheduled appointments. Developers can use this data to analyze appointment trends for providers. Authorization is required to access this API."
basePath: /analytics/api
schemes:
  - http
paths:
  /provider/appointments:
    post:
      tags: [Provider Dashboard]
      summary: "Retrieve Provider Appointment Data"
      description: "This API provides appointment data for providers, including the count of cancelled, re-scheduled, and scheduled appointments. Developers can use this data to analyze appointment trends for providers. Authorization is required to access this API. Note: Only 1 week and 1 month time filters apply; other filters do not."
      parameters: []
      requestBody:
        description: "Request body for filters."
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                time_span_id:
                  type: integer
                  description: >
                    An integer representing the time period:
                    - 1: 1 week
                    - 2: 1 month
                  enum: [1, 2]
                provider_ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                facility_location_ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                fromDate:
                  type: string
                  format: date
                  description: >
                    Retrieve data for appointments from this date.
                    Format: YYYY-MM-DD
                toDate:
                  type: string
                  format: date
                  description: >
                    Retrieve data for appointments up to this date.
                    Format: YYYY-MM-DD
                granularity_type_id:
                  type: integer
                  description: >
                    An integer representing the granularity:
                    - 1: daily
                    - 2: weekly
                    - 3: monthly
                    - 4: yearly
                  enum: [1, 2, 3, 4]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: integer
                  result:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          Cancelled:
                            type: integer
                          re_scheduled:
                            type: integer
                          scheduled:
                            type: integer
                          Cancelled_list:
                            type: array
                            items:
                              type: object
                          re_scheduled_list:
                            type: array
                            items:
                              type: object
                          scheduled_list:
                            type: array
                            items:
                              type: object
        400:
          description: "Bad request"
        401:
          description: "You are not authorized"
        404:
          description: "Data not found for given parameters"
        500:
          description: "Internal server error"
