swagger: "2.0"
info:
  version: "1.0.0"
  title: "Provider Appointments Analysis"
description: "API to retrieve appointment analysis data for providers, including granular data by date and appointment types. Developers can use this data to analyze appointment trends for providers. Authorization is required to access this API."
basePath: /analytics/api
schemes:
  - http
paths:
  /provider/appointments-analysis:
    post:
      tags: [Provider Dashboard]
      summary: "Retrieve Provider Appointment Analysis Data"
      description: "This API provides appointment analysis data for providers, including granular data by date and appointment types. Developers can use this data to analyze appointment trends for providers. Authorization is required to access this API."
      produces:
        - application/json
      requestBody:
        description: "Request body for filtering appointment analysis data."
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                time_span_id:
                  type: integer
                  description: >
                    An integer representing the time period:
                    - 1: 1 week
                    - 2: 1 month
                  enum: [1, 2]
                provider_ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                facility_location_ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                fromDate:
                  type: string
                  format: date
                  description: >
                    Retrieve data for appointments from this date.
                    Format: YYYY-MM-DD
                toDate:
                  type: string
                  format: date
                  description: >
                    Retrieve data for appointments up to this date.
                    Format: YYYY-MM-DD
                granularity_type_id:
                  type: integer
                  description: >
                    An integer representing the granularity:
                    - 1: daily
                    - 2: weekly
                    - 3: monthly
                    - 4: yearly
                  enum: [1, 2, 3, 4]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/definitions/AppointmentAnalysisResponse"
        "404":
          description: "Data not found"
definitions:
  AppointmentAnalysisResponse:
    type: object
    properties:
      data:
        type: object
        properties:
          granular_data:
            type: array
            items:
              type: object
              properties:
                date_label:
                  type: string
                follow_up:
                  type: integer
                completed:
                  type: integer
                re_evaluation:
                  type: integer
                initial_evaluation:
                  type: integer
          Cancelled:
            type: integer
          follow_up:
            type: integer
          Scheduled:
            type: integer
          completed:
            type: integer
          re_evaluation:
            type: integer
          initial_evaluation:
            type: integer
