swagger: "2.0"
info:
  version: "1.0.0"
  title: "Practice Manager Dashboard API"
  description: "API to Retrieve whole data or filters based on parameters for Practice Manager"
tags:
  - name: Practice Manager Dashboard
    description: "API to Retrieve whole data or filters based on parameters for Practice Manager"
basePath: /analytics/api
schemes:
  - http
paths:
  /practice-manager/denial-type:
    post:
      tags: [Practice Manager Dashboard]
      summary: "Analytic report to calculate occurrence and percentage against each Denial type"
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: "Request body for filtering Denial Type report"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                time_span_id:
                  description: "An integer representing the time period (1: 1 week, 2: 1 month, 3: 6 months, 4: 1 year, 5: Month to Date)"
                  required: false
                  type: integer
                  enum: [1, 2, 3, 4, 5]
                month_id:
                  description: "An integer representing the month in months dropdown (1: January, 2: February, 3: March, 4: April, 5: May, 6: June, 7: July, 8: August, 9: September, 10: October, 11: November, 12: December)"
                  required: false
                  type: integer
                  enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
                speciality_ids:
                  description: "Comma-separated list of speciality IDs"
                  required: false
                  type: string
                provider_ids:
                  description: "Comma-separated list of provider IDs"
                  required: false
                  type: string
                facility_location_ids:
                  description: "Comma-separated list of facility location IDs"
                  required: false
                  type: string
                fromDate:
                  description: "Retrieve data for summary charts from this date (Format: YYYY-MM-DD)"
                  required: false
                  type: string
                  format: date
                toDate:
                  description: "Retrieve data for summary charts up to this date (Format: YYYY-MM-DD)"
                  required: false
                  type: string
                  format: date
                granularity_type_id:
                  description: "An integer representing the granularity (1: daily, 2: weekly, 3: monthly, 4: yearly)"
                  required: false
                  type: integer
                  enum: [1, 2, 3, 4]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Filtered Data returned"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: integer
                  result:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          fullData:
                            type: array
                            items:
                              type: object
                              properties:
                                denial_type_id:
                                  type: integer
                                denial_type_name:
                                  type: string
                                denial_count:
                                  type: string
                                denial_percentage:
                                  type: string
                          labels:
                            type: array
                            items:
                              type: string
                          labelVals:
                            type: array
                            items:
                              type: string
                          labelPercentage:
                            type: array
                            items:
                              type: number
        "404":
          description: "Data not found"
definitions:
  denialresponseData:
    type: object
    properties:
      fullData:
        type: array
        items:
          type: object
          properties:
            denial_type_id:
              type: integer
              example: 1
            denial_type_name:
              type: string
              example: "Do Not LIT Or ARB"
            denial_count:
              type: string
              example: "20"
            denial_percentage:
              type: string
              example: "71.42"
      labels:
        type: array
        items:
          type: string
      labelVals:
        type: array
        items:
          type: string
      labelPercentage:
        type: array
        items:
          type: number
