swagger: "2.0"
info:
  version: "1.0.0"
  title: "Practice Manager Dashboard API"
  description: "This API provides summary charts data for various metrics like Denial Rate, Cancellation Rate, Unbilled Visits, Appointment Rate, and Wait Time. It can be used by developers to build charts for insights. Authorization is required to access this API."
basePath: /analytics/api
schemes:
  - http
paths:
  /practice-manager/summaryCharts:
    post:
      tags: [Practice Manager Dashboard]
      summary: "Retrieve summary charts data"
      description: "This API provides summary charts data for various metrics like Denial Rate, Cancellation Rate, Unbilled Visits, Appointment Rate, and Wait Time. It can be used by developers to build charts for insights. Authorization is required to access this API."
      parameters: []
      requestBody:
        description: "Request body for summary charts data."
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                time_span_id:
                  type: integer
                  description: >
                    An integer representing the time period:
                    - 1: 1 week
                    - 2: 1 month
                    - 3: 6 months
                    - 4: 1 year
                    - 5: Month to Date
                  enum: [1, 2, 3, 4, 5]
                month_id:
                  type: integer
                  description: >
                    An integer representing the month in months dropdown:
                    - 1: January
                    - 2: February
                    - 3: March
                    - 4: April
                    - 5: May
                    - 6: June
                    - 7: July
                    - 8: August
                    - 9: September
                    - 10: October
                    - 11: November
                    - 12: December
                  enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
                speciality_ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                provider_ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                facility_location_ids:
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                fromDate:
                  type: string
                  format: date
                  description: >
                    Retrieve data for summary charts from this date.
                    Format: YYYY-MM-DD
                toDate:
                  type: string
                  format: date
                  description: >
                    Retrieve data for summary charts up to this date.
                    Format: YYYY-MM-DD
                granularity_type_id:
                  type: integer
                  description: >
                    An integer representing the granularity:
                    - 1: daily
                    - 2: weekly
                    - 3: monthly
                    - 4: yearly
                  enum: [1, 2, 3, 4]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: integer
                  result:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          Denial_Rate_current_number:
                            type: string
                          Denial_Rate_current_total_number:
                            type: string
                          Denial_Rate_previous_number:
                            type: string
                          Denial_Rate_previous_total_number:
                            type: string
                          Denial_Rate_current:
                            type: string
                          Denial_Rate_previous:
                            type: string
                          Denial_Rate_changed:
                            type: string
                          Denial_is_Positive:
                            type: boolean
                          Cancel_current_number:
                            type: string
                          Cancel_current_total_number:
                            type: string
                          Cancel_previous_number:
                            type: string
                          Cancel_previous_total_number:
                            type: string
                          Cancel_current:
                            type: string
                          Cancel_previous:
                            type: string
                          Cancel_changed:
                            type: string
                          Cancel_is_Positive:
                            type: boolean
                          Unbilled_Visit_current_number:
                            type: string
                          Unbilled_Visit_current_total_number:
                            type: string
                          Unbilled_Visit_previous_number:
                            type: string
                          Unbilled_Visit_previous_total_number:
                            type: string
                          Unbilled_Visit_current:
                            type: string
                          Unbilled_Visit_previous:
                            type: string
                          Unbilled_Visit_changed:
                            type: string
                          Unbilled_is_Positive:
                            type: boolean
                          Appointment_current_number:
                            type: string
                          Appointment_current_total_number:
                            type: string
                          Appointment_previous_number:
                            type: string
                          Appointment_previous_total_number:
                            type: string
                          Appointment_current:
                            type: string
                          Appointment_previous:
                            type: string
                          Appointment_changed:
                            type: string
                          Appointment_is_Positive:
                            type: boolean
                          WaitTime_current:
                            type: string
                          WaitTime_previous:
                            type: string
                          WaitTime_changed:
                            type: string
                          WaitTime_is_Positive:
                            type: boolean
        400:
          description: "Bad request"
        401:
          description: "You are not authorized"
        404:
          description: "Data not found for given parameters"
        500:
          description: "Internal server error"
